/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import SQL.Conexion;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import javax.swing.JComboBox;


/**
 *
 * @author davpa
 */
public class GUIRegMascota extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegMascota
     */
    private boolean agregado = false;
    String txt;
    Object[] fila;
    String especie;
    
    public GUIRegMascota() {
        initComponents();
        
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
        cmbColor.removeAllItems();
        cmbEspecie.removeAllItems();
        cmbRaza.removeAllItems();
        cmbEnfermedad.removeAllItems();
        cmbVacuna.removeAllItems();
        
        //rellenarComboBox();
        llenarEspecie();
        llenarColor();
        llenarEnfermedad();
        llenarVacuna();
        cmbEspecie.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                

                if(!isEspecieAgregada()){
                  especie=cmbEspecie.getSelectedItem().toString();
                  setAgreEspecie(false);
                  llenarRaza(especie);
                }
        }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreMasc = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbEspecie = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbRaza = new javax.swing.JComboBox<>();
        cmbEspecieAdd = new javax.swing.JToggleButton();
        cmbRazaAdd = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbEnfermedad = new javax.swing.JComboBox<>();
        cmbVacuna = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        btnEnfermedad = new javax.swing.JToggleButton();
        btnVacuna = new javax.swing.JToggleButton();

        jButton3.setText("jButton3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Mascota"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Peso actual:");

        jLabel4.setText("Color: ");

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Especie:");

        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Raza:");

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEspecieAdd.setText("...");
        cmbEspecieAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecieAddActionPerformed(evt);
            }
        });

        cmbRazaAdd.setText("...");
        cmbRazaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRazaAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEspecieAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbRazaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEspecieAdd)
                    .addComponent(cmbRazaAdd))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jButton2.setText("REGISTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("A continuación, registre la primera cita médica:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cita Medica"));

        jLabel9.setText("Fecha:");

        jLabel10.setText("Vacuna:");

        jLabel11.setText("Enfermedad:");

        cmbEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEnfermedad.setText("...");
        btnEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfermedadActionPerformed(evt);
            }
        });

        btnVacuna.setText("...");
        btnVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(46, 46, 46))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(79, 79, 79)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(71, 71, 71)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbEnfermedad, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                    .addComponent(cmbVacuna, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnfermedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVacuna))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        GUIRegUsuario.getId_cliente();
        
        String nombre = txtNombreMasc.getText();
        double peso = Double.parseDouble(txtPeso.getText());
        String color = cmbColor.getSelectedItem().toString();
        int id_color;
        String especie1 = cmbEspecie.getSelectedItem().toString();
        int id_especie;
        String raza = cmbRaza.getSelectedItem().toString();
        int id_raza;
        String fecha = txtFecha.getText();
        String enfer = cmbEnfermedad.getSelectedItem().toString();
        int id_enfermedad;
        String vacuna = cmbVacuna.getSelectedItem().toString();
        int id_vacuna;
        
        
        
        
        int id_historial = Conexion.llenarID("MASCOTA_", "ID_HISTORIAL");

        id_color = getID("COLORS", "ID_COLORS", color);
        id_enfermedad = getIDenf("ENFERMEDAD", "ID_ENFERMEDAD", enfer);
        id_especie = getID("ESPECIE", "ID_ESPECIE", especie1);
        id_raza = getID("RAZA", "ID_RAZA", raza);
        id_vacuna = getIDvac("VACUNACION", "ID_VACUNACION", vacuna);
        
        try{
            PreparedStatement ps;
            Connection con = Conexion.getConexion();
            
            ps = con.prepareStatement("set xact_abort on\n" +"begin distributed transaction\n" +
"insert into MASCOTA_ (ID_HISTORIAL, ID_COLORS, ID_CLIENTE, ID_ESPECIE, ID_RAZA, NOMBRE, PESO_ACTUAL, CIUDAD) values (?,?,?,?,?,?,?,?)\n" +
"commit transaction");
            ps.setInt(1, id_historial);
            ps.setInt(2, id_color);
            ps.setInt(3, GUIRegUsuario.getId_cliente());
            ps.setInt(4, id_especie);
            ps.setInt(5, id_raza);
            ps.setString(6, nombre);
            ps.setDouble(7, peso);
            ps.setString(8, Conexion.getCiudad());
            ps.executeUpdate();
            
            
            
            int linea = Conexion.llenarID("HISTORIAL_", "LINEA_HISTORIAL");
            ps = con.prepareStatement("set xact_abort on\n" +"begin distributed transaction\n" +
"insert into HISTORIAL_ (ID_HISTORIAL, LINEA_HISTORIAL, ID_VACUNACION, ID_ENFERMEDAD, FECHA_CITAMEDICA, CIUDAD) values (?,?,?,?,?,?)\n" +
"commit transaction");
            ps.setInt(1, id_historial);
            ps.setInt(2, linea);
            ps.setInt(3, id_vacuna);
            ps.setInt(4, id_enfermedad);
            ps.setString(5, fecha);
            ps.setString(6, Conexion.getCiudad());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro realizado con exito");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private int getID(String tabla, String id, String nombre){
        int idFinal=0;
        try{
            PreparedStatement ps;
            ResultSet rs;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT "+id +" from "+tabla +" where nombre=?");
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){

                        idFinal = rs.getInt(indice +1);

                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        return idFinal;
        
    }
    
    private int getIDenf(String tabla, String id, String nombre){
        int idFinal=0;
        try{
            PreparedStatement ps;
            ResultSet rs;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT "+id +" from "+tabla +" where NOM_ENFERMEDAD=?");
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){
                        idFinal = rs.getInt(indice +1);

                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        return idFinal;
        
    }
    private int getIDvac(String tabla, String id, String nombre){
        int idFinal=0;
        try{
            PreparedStatement ps;
            ResultSet rs;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT "+id +" from "+tabla +" where NOM_VACUNA=?");
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){

                        idFinal = rs.getInt(indice +1);

                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        return idFinal;
        
    }
    
    private void cmbEspecieAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecieAddActionPerformed
        // TODO add your handling code here:
        txt = JOptionPane.showInputDialog("Ingrese especie");
        setAgreEspecie(true);
        //insercion
        agregarEspecie(txt);
        //insercion
        setAgreEspecie(false);
        JOptionPane.showMessageDialog(null, "Ingrese almenos una raza");
        int op;
        do{
            String raza = JOptionPane.showInputDialog("Ingrese la raza");
            agregarRaza(txt, raza);
            op = JOptionPane.showConfirmDialog(null, "¿Desea ingresar otra raza?");///NO=1,2..... SI=0

            //cod Insercion especie y raza
        }while(op==0);
        
        llenarEspecie();
        
    }//GEN-LAST:event_cmbEspecieAddActionPerformed

    private void cmbRazaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRazaAddActionPerformed
        // TODO add your handling code here:
        
        String razaAdd = cmbEspecie.getSelectedItem().toString();
        
        String resp = JOptionPane.showInputDialog(null, "Ingrese la raza que desea agregar en "+razaAdd);
        agregarRaza(razaAdd, resp);
        llenarRaza(especie);

        //cod Insercion raza
    }//GEN-LAST:event_cmbRazaAddActionPerformed

    private void btnEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfermedadActionPerformed
        // TODO add your handling code here:
        
        String enf = JOptionPane.showInputDialog(null, "Ingrese la enfermedad que desea agregar");
        agregarEnfermedad(enf);
        llenarEnfermedad();
        
        
        
    }//GEN-LAST:event_btnEnfermedadActionPerformed

    private void btnVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunaActionPerformed
        // TODO add your handling code here:
        
        String enf = JOptionPane.showInputDialog(null, "Ingrese la Vacuna que desea agregar");
        agregarVacuna(enf);
        llenarVacuna();
        
        
    }//GEN-LAST:event_btnVacunaActionPerformed

    private void agregarEspecie(String especie){
                  
        try{
            PreparedStatement ps;
            Connection con = Conexion.getConexion();
            
            int id = Conexion.llenarID("ESPECIE", "ID_ESPECIE");
            ps = con.prepareStatement("insert into ESPECIE (ID_ESPECIE,NOMBRE) values (?,?)");
            ps.setInt(1, id);
            ps.setString(2, especie);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro realizado con exito");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void agregarRaza(String especie, String raza){
                  
        try{
            
            ResultSet rs;
            ResultSetMetaData rsmd;
            PreparedStatement ps;
            Connection con = Conexion.getConexion();

            //Encontrar la id correspondiente a una raza segun su especie
            PreparedStatement ps1;
            int columnas;
            int idEspecie=0;
            ps1 = con.prepareStatement("Select ID_ESPECIE from ESPECIE where nombre = ?");
            ps1.setString(1, especie);
            rs = ps1.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){
                    idEspecie = (int) rs.getObject(indice +1);
                }
            }

            int id_raza = Conexion.llenarID("RAZA", "ID_RAZA");
            ps = con.prepareStatement("insert into RAZA (ID_ESPECIE,ID_RAZA,NOMBRE) values (?,?,?)");
            ps.setInt(1, idEspecie);
            ps.setInt(2, id_raza);
            ps.setString(3, raza);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro realizado con exito");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void agregarEnfermedad(String enf){
        
        try{
            PreparedStatement ps;
            Connection con = Conexion.getConexion();
            
            int id = Conexion.llenarID("ENFERMEDAD", "ID_ENFERMEDAD");
            ps = con.prepareStatement("insert into ENFERMEDAD (ID_ENFERMEDAD,NOM_ENFERMEDAD) values (?,?)");
            ps.setInt(1, id);
            ps.setString(2, enf);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro realizado con exito");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    private void agregarVacuna(String vac){
        
        try{
            PreparedStatement ps;
            Connection con = Conexion.getConexion();
            
            int id = Conexion.llenarID("VACUNACION", "ID_VACUNACION");
            ps = con.prepareStatement("insert into VACUNACION (ID_VACUNACION,NOM_VACUNA) values (?,?)");
            ps.setInt(1, id);
            ps.setString(2, vac);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro realizado con exito");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    private void llenarRaza(String especie){
        
        cmbRaza.removeAllItems();
        int columnas;
        int filas=0;
        try{
            ResultSet rs;
            PreparedStatement ps;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();

            ps = con.prepareStatement("SELECT raza.nombre FROM especie inner join raza on especie.id_especie=raza.id_especie where especie.nombre=?");
            ps.setString(1, especie);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            
            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){
                    cmbRaza.addItem((String) rs.getObject(indice +1));
                }
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    
    
    
    private void llenarColor(){
        
        
        int columnas;
        try{
            ResultSet rs;
            PreparedStatement ps;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT nombre FROM colors");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            
            while(rs.next()){

                for(int indice =0; indice < columnas; indice++){
                    cmbColor.addItem((String) rs.getObject(indice +1));
                }
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    private void llenarEnfermedad(){
        
        cmbEnfermedad.removeAllItems();
        int columnas;
        try{
            ResultSet rs;
            PreparedStatement ps;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT NOM_ENFERMEDAD FROM Enfermedad");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            
            while(rs.next()){

                for(int indice =0; indice < columnas; indice++){
                    cmbEnfermedad.addItem((String) rs.getObject(indice +1));
                }
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    private void llenarVacuna(){
        int columnas;
        try{
            ResultSet rs;
            PreparedStatement ps;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT NOM_VACUNA FROM VACUNACION");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){

                for(int indice =0; indice < columnas; indice++){
                    cmbVacuna.addItem((String) rs.getObject(indice +1));
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    private void llenarEspecie(){
        

        int columnas;
        try{
            ResultSet rs;
            PreparedStatement ps;
            ResultSetMetaData rsmd;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT nombre FROM especie");
            
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();

            while(rs.next()){
                for(int indice =0; indice < columnas; indice++){
                    cmbEspecie.addItem((String) rs.getObject(indice +1));
                }
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    private boolean isEspecieAgregada(){
        
        return agregado;
    }
    
    private void setAgreEspecie(boolean a){
        this.agregado = a;
    }
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEnfermedad;
    private javax.swing.JToggleButton btnVacuna;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbEnfermedad;
    private javax.swing.JComboBox<String> cmbEspecie;
    private javax.swing.JToggleButton cmbEspecieAdd;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JToggleButton cmbRazaAdd;
    private javax.swing.JComboBox<String> cmbVacuna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreMasc;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
